buildscript {
    repositories {
        maven {
            url 'http://localhost:8080/snapshots'
        }

        mavenCentral()
    }

    dependencies {
        classpath 'info.gianlucacosta.aurora:aurora:10.0.0-SNAPSHOT'
    }
}

plugins {
    id 'java'
    id 'maven'
}

apply plugin: 'info.gianlucacosta.aurora'

group 'info.gianlucacosta.zephyros'
archivesBaseName = 'zephyros-core'
version '2.0.0-SNAPSHOT'

description = 'Core utilities for modern Java'

dependencies {
    testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-all:1.3'
}

aurora {
    gitHubUser = 'giancosta86'

    author {
        name = 'Gianluca Costa'
        email = 'gianluca@gianlucacosta.info'
        url = 'http://gianlucacosta.info/'
    }

    mavenDeploy {
        url = 'http://localhost:8080/snapshots'
    }
}
